### ISSUE TITLE
merge the simple version and the expert version into one app

### ISSUE THREAD

**Issue by kmillesc** [Pachka/mwss-App#10]
Mettre la version simplifiée et la version experte sur une seule app.

Dans la side bar, changement des onglets : 
- Presentation
- Get started (ou autre nom représentant la version simplifiée) : sans sous onglet, une seule "page"
- Version experte (trouver un nom) avec des sous onglets : Initialization, Simulation, More parameters
- About

**Comment by qleclerc** [comment]
Closing since this has been implemented in main after merging a pull request from the simple_version branch https://github.com/Pachka/mwss-App/pull/30
