### ISSUE TITLE
New result visualisation for simple version

### ISSUE THREAD

**Issue by qleclerc** [Pachka/mwss-App#23]
New results in simple version of the app should display:

1. Two lines with key numerical results, like current version
2. Plot to display peak incidence per ward during the simulation. Suggestion: a plot with one facet for staff, one facet for patients, x axis as wards, y axis as peak incidence value.
3. Plot to display non-cumulative incidence at hospital level. Suggestion: one line for staff, one for patients, x axis time, y axis incidence OR relative incidence (% of maximum staff/patients in hospital)
4. Keep current daily risk by service plot, with fixed default number of colors in legend, and removing all layout options
5. Keep current number of tests plot, for the whole facility and patients and staff combined. Set default aggregation to median over 7 days.
6. For all plots: remove the png/pdf export choice, set png as default.

**Comment by kmillesc** [comment]
plot généré par la fonction plotsoutputUI du fichier plotsoutputModule.R dans le dossier functions

**Comment by qleclerc** [comment]
New results in simple version of the app should display:

1. Two lines with key numerical results, like current version
2. Plot to display peak incidence per ward during the simulation. Suggestion: a plot with one facet for staff, one facet for patients, x axis as wards, y axis as peak incidence value.
3. Plot to display non-cumulative incidence at hospital level. Suggestion: one line for staff, one for patients, x axis time, y axis incidence OR relative incidence (% of maximum staff/patients in hospital) **[ONGOING QUENTIN]**
4. Keep current daily risk by service plot, with fixed default number of colors in legend, and removing all layout options **[DONE]**
5. Keep current number of tests plot, for the whole facility and patients and staff combined. Set default aggregation to median over 7 days. **[CAMILLE -  travaille actuellement pour enlever]**
6. For all plots: remove the png/pdf export choice, set png as default. **[DONE]**

**Comment by qleclerc** [comment]
All new results plots have been created in the branch sv_plot.
Suggestion to close this issue, and open new ones to edit the new plots.

**Comment by qleclerc** [comment]
Closing and linking to the new issues to improve the new plots: 

- https://github.com/Pachka/mwss-App/issues/35
- https://github.com/Pachka/mwss-App/issues/34
- https://github.com/Pachka/mwss-App/issues/33
