### ISSUE TITLE
Control and surveillance choices

### ISSUE THREAD

**Issue by kmillesc** [Pachka/mwss-App#25]
Dans la box "Control and surveillance" de la page "Simulations" de l'onglet Version simple : 
But = ne plus avoir de box qui apparaissent quand on coche une des tick box 

- Tick box : "Impose confinement/contact restriction to detected patients?" --> si coché, avoir par défaut "level of contact restriction or probability to implement contact restriction (0: no contact restriction, 1: no contact)." à 1 ; si non coché, avoir par défaut 0 (il n'y a plus de "box" qui apparait pour demander la valeur du level of contact restriction quand on coche)
- Tick box : "Implement random tests at regular intervals?" --> à diviser en 2 tick box directement : "Implement random tests at regular intervals for patients?" et "Implement random tests at regular intervals for professionnals?" avec les paramètres associés mis par défaut pour patients et professionnals
- Tick box : "Implement a screening area at patient admission including contact restriction/clinical examination/test?" à simplifier en "Implement a test at patient admission" avec les paramètres des tests déjà mis par défaut

**Comment by sophiechervet** [comment]
Commit 09/02/23 10h45
