### ISSUE TITLE
Fix data.table/dplyr coding in new simplified plots

### ISSUE THREAD

**Issue by qleclerc** [Pachka/mwss-App#34]
The code for new plots must be reworked to run more efficiently, as there is currently time lost by switching between data.table and dplyr structures.

See `functions/plotsoutputModule.R`, lines 391-432 and lines 595-665

**Comment by Pachka** [comment]
@qleclerc, I fixed the melt issue but the plot are still taking time to display.... Maybe double check the plot content before closing the issue
